### ISSUE TITLE
Python: permission denied errors

### ISSUE THREAD

**Issue by Sporknife** [asus-linux-drivers/asus-accel-tablet-mode-driver#1]
Hello, I just installed the driver and I get permission errors in the log. Sorry for the shitty description.

[asus-error.log](https://github.com/asus-linux-drivers/asus-accel-tablet-mode-driver/files/13854793/asus-error.log)

**Comment by ldrahnik** [comment]
Does it manually work `LOG=DEBUG sudo -E ./asus_accel_driver.py "default"`?

**Comment by ldrahnik** [comment]
Solution for permissions error I will commit soon, I know what Is wrong, thank you.

**Comment by ldrahnik** [comment]
Try now and please let me know.

**Comment by Sporknife** [comment]
works.
