### ISSUE TITLE
Going forward

### ISSUE THREAD

**Issue by Sporknife** [asus-linux-drivers/asus-accel-tablet-mode-driver#2]
How can we get some attention in linux kernel land to get fully fixed? The way I see it, this isn't a perfect fix because you cant know how the users laptop is currently turned and at which angle they sit.

**Comment by ldrahnik** [comment]
You are right that it is a known limitation of the solution using an accelerometer. It is generally usable only with premise tablet mode for user means laptop's display almost in horizontal position but even this may be for someone good enough.

**Comment by Sporknife** [comment]
This is still better than what amd has got (which is nothing).

**Comment by Sporknife** [comment]
Wrote an email to the mantainer of amd-fsh.

**Comment by ldrahnik** [comment]
@Sporknife Looking forward to the answer :) I created [a comment](https://bugzilla.kernel.org/show_bug.cgi?id=214675) what I know about this issue

**Comment by ldrahnik** [comment]
Discussion continues [here](https://github.com/orgs/asus-linux-drivers/discussions/4)
